image_splitter_node:
  ros__parameters:
    video_device: 0
    width: 2560
    height: 720
    fps: 30
    frame_id: "camera_link"
    rotation_angle: 180
    jpeg_quality: 80

esp32_serial_node:
  ros__parameters:
    display_rate: 1.0

ins_ekf_node:
  ros__parameters:
    ekf_mode: 16
    imu_topic: "/imu/data"
    gnss_topic: "/gnss/fix"
    mag_topic: "/mag/data"
    baro_topic: "/pressure"
    vel_topic: "/velocity"
    enable_gnss_pos: true
    enable_gnss_vel: true
    enable_mag: true
    enable_baro: true
    enable_agv: true
    enable_nhc: false
    enable_zupt_hor: false
    publish_tf: true
    map_frame: "map"
    base_link_frame: "base_link"

